### ISSUE TITLE
BT home misses packages from Shelly BLU devices

### ISSUE THREAD

**Issue by Denmark7000** [home-assistant/bthome.io#46]
I see previous post re. package misses from BT devices. 
I run Shelly BLU devices. 
In order to monitor the situation:
I have a script running on Shelly 1Mini Gen3 that holds a virtual component = a number variable, and second digit in this is equal to my door/window sensor. Example Open = 910000 Closed = 900000, so second digits is either 1 og 0.
When I display in Home Assistant both:
(1) The original BLU device entities 
(2) My virtual component
It is clearly seen that the BLU device entities do not pass into Home Assistant correctly.
Also the log shows that only some packages are read by Home Assistant - whereas the virtual component react on each open/close of the door.
See screenshot.
![Step1_Open](https://github.com/home-assistant/bthome.io/assets/165161465/42d85662-65e8-449d-acb1-7bc610e41df1)
![Step2_Closed](https://github.com/home-assistant/bthome.io/assets/165161465/7226b25d-e700-4420-abd4-4e3f3946b62a)
![Step3_OutOfSync](https://github.com/home-assistant/bthome.io/assets/165161465/dab17c0a-f169-4385-b42a-427f1f95ed72)
![Steps_in_Logbook](https://github.com/home-assistant/bthome.io/assets/165161465/73aea101-8cf6-4e3e-94a0-2da484b9f11e)

**Comment by Ernst79** [comment]
Sorry I missed your message. Please open this issue on the Home Assistant core repo. This repo only deals with the documentation of BTHome, not with the implementation in HA.

I'm sorry that I close this issue here, but there will be more support in the HA core repo, where also the Bluetooth developers of HA can help you out. I think your issue is more related to the Bluetooth or the combination of the Bluetooth integration and the BTHome integration in HA.
